import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/hero/Hero";
import ServicesSection from "@/components/servicesSection/ServicesSection";
import TechsSection from "@/components/techsSection/TechsSection";
import AboutSection from "@/components/aboutSection/AboutSection";
import PortfolioSection from "@/components/portfolioSection/PortfolioSection";
import ClientReview from "@/components/clientReview/ClientReview";
import Contact from "@/components/contact/Contact";
import Footer from "@/components/footer/Footer";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Octa.Codes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <Hero />
       <ServicesSection />
       <TechsSection />
       <AboutSection />
       <PortfolioSection />
       <ClientReview />
      
      </main>
    </>
  );
}
